# Generated by Django 5.2.7 on 2026-01-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apartment Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Building Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='image_of_building',
            field=models.ImageField(blank=True, null=True, upload_to='address_images/', verbose_name='Image of Building'),
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Neighborhood'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('jeddah - جدة', 'Jeddah')], default='jeddah - جدة', max_length=100, verbose_name='City'),
        ),
    ]
