# Generated by Django 5.2.7 on 2026-04-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_options_alter_customer_options_and_more'),
        ('orders', '0008_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='orders.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('customer', 'مستخدم عادي'), ('delivery_rep', 'مندوب'), ('store_manager', 'مدير متجر'), ('system_admin', 'مدير النظام')], default='customer', max_length=30, verbose_name='Role'),
        ),
    ]
