# Generated by Django 5.2.7 on 2026-04-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_branch_order_representative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'الطلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'عنصر الطلب', 'verbose_name_plural': 'عناصر الطلب'},
        ),
    ]
