# Generated by Django 5.2.7 on 2026-04-19 (modified manually)
# Strategy: add slug as nullable non-unique first, then data migration fills values,
# then a separate migration adds the unique constraint.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ('display_order', 'id'), 'verbose_name': 'حالة الطلب', 'verbose_name_plural': 'حالات الطلبات'},
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(default='#6B7280', help_text='كود اللون HEX للبادج', max_length=20, verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='افتراضي للطلبات الجديدة'),
        ),
        # Add slug as nullable + no unique first — data migration will fill it
        migrations.AddField(
            model_name='orderstatus',
            name='slug',
            field=models.SlugField(
                max_length=50,
                null=True,
                blank=True,
                help_text='مثال: pending, processing — لا تغيّره بعد الإنشاء',
                verbose_name='المعرّف البرمجي',
            ),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
    ]
