# Generated by Django 5.2.7 on 2026-04-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_section_options_remove_section_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'البانر الإعلاني', 'verbose_name_plural': 'البانرات الإعلانية'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'الشركة', 'verbose_name_plural': 'الشركات'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['ordering'], 'verbose_name': 'القسم', 'verbose_name_plural': 'الأقسام'},
        ),
    ]
