# Generated by Django 5.2.7 on 2025-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_linkvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='basePrice',
            field=models.FloatField(default=0, verbose_name='Base Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='discountedPrice',
            field=models.FloatField(default=0, verbose_name='Discounted Price'),
        ),
    ]
