# Generated by Django 5.2.7 on 2025-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_price_product_baseprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('single', 'منتج أساسي مفرد'), ('bundle', 'عرض مجمّع')], default='single', max_length=10, verbose_name='Product Type'),
        ),
    ]
