# Generated by Django 5.2.7 on 2026-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='basePrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discountedPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.FloatField(default=0, verbose_name='New Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0, verbose_name='Old Price'),
        ),
    ]
