# Generated by Django 5.2.7 on 2026-01-08 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_sales_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product', verbose_name='Bundle')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_bundles', to='products.product', verbose_name='Item')),
            ],
        ),
    ]
