# Generated by Django 5.2.7 on 2026-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_bundleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleitem',
            name='price_in_bundle',
            field=models.FloatField(default=0, verbose_name='Price in Bundle'),
        ),
        migrations.AlterUniqueTogether(
            name='bundleitem',
            unique_together={('bundle', 'item')},
        ),
    ]
