# Generated by Django 5.2.7 on 2026-01-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_bundleitem_price_in_bundle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleitem',
            name='description',
            field=models.TextField(blank=True, max_length=40000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundle_items', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_bundles', to='products.product', verbose_name='Product'),
        ),
    ]
