# Generated by Django 5.2.7 on 2026-01-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bundleitem_description_bundleitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='product_category', to='products.category', verbose_name='Category'),
        ),
    ]
