# Generated by Django 5.1.6 on 2026-01-09 04:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(upload_to='bundles', verbose_name='Image')),
                ('description', models.TextField(blank=True, max_length=40000, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='price_in_bundle',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price in Bundle'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterUniqueTogether(
            name='bundleitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.bundle', verbose_name='Bundle'),
        ),
        migrations.AlterUniqueTogether(
            name='bundleitem',
            unique_together={('item', 'bundle')},
        ),
        migrations.RemoveField(
            model_name='bundleitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bundleitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='bundleitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bundleitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bundleitem',
            name='total_price',
        ),
    ]
