# Generated by Django 5.1.6 on 2026-01-09 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_bundle_alter_bundleitem_price_in_bundle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='create_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create at'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
