# Generated by Django 5.2.7 on 2026-01-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_bundle_active_bundle_create_at_bundle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.FloatField(blank=True, default=0, verbose_name='السعر المخفض (اختياري)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0, verbose_name='السعر الأصلي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='Slug'),
        ),
    ]
