# Generated by Django 5.2.7 on 2026-04-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_brand_seo_canonical_url_brand_seo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'الوسم الترويجي',
                'verbose_name_plural': 'الوسوم الترويجية',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'العلامة التجارية', 'verbose_name_plural': 'العلامات التجارية'},
        ),
        migrations.AlterModelOptions(
            name='bundle',
            options={'verbose_name': 'الباقة', 'verbose_name_plural': 'الباقات'},
        ),
        migrations.AlterModelOptions(
            name='bundleitem',
            options={'verbose_name': 'عنصر الباقة', 'verbose_name_plural': 'عناصر الباقة'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'التصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'العرض', 'verbose_name_plural': 'العروض'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'صور المنتج', 'verbose_name_plural': 'صور المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'التقييم', 'verbose_name_plural': 'التقييمات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag',
        ),
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.flag', verbose_name='Flag'),
        ),
    ]
