# Generated by Django 5.2.7 on 2026-04-19 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_flag_alter_brand_options_alter_bundle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب الظهور في الصفحة الرئيسية', verbose_name='الترتيب')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'المنتج المميز (للرئيسية)',
                'verbose_name_plural': 'المنتجات المميزة (للرئيسية) 🌟',
                'ordering': ['order', '-id'],
            },
        ),
    ]
