# Generated by Django 5.2.7 on 2026-04-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سلة التسوق', 'verbose_name_plural': 'سلال التسوق'},
        ),
    ]
