# Generated by Django 5.2.7 on 2026-03-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Map Link'),
        ),
    ]
