# Generated by Django 5.2.7 on 2026-04-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_country_address_latitude_address_longitude_and_more'),
        ('accounts', '0003_address_location_link'),
    ]

    operations = [
    ]
