# Generated by Django 5.2.7 on 2026-04-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otptoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'العنوان', 'verbose_name_plural': 'العناوين'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'العميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='otptoken',
            options={'verbose_name': 'رمز التحقق', 'verbose_name_plural': 'رموز التحقق'},
        ),
    ]
