# Generated by Django 5.2.7 on 2025-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(default='متجر الكتروني', max_length=100),
        ),
    ]
