# Generated by Django 5.2.7 on 2025-11-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_company_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='Banner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cover',
            field=models.ImageField(upload_to='Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='Company'),
        ),
    ]
