# Generated by Django 5.2.7 on 2025-11-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_banner_image_alter_company_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('offer', 'offer'), ('bundle', 'bundle')], default='offer', max_length=10),
        ),
    ]
