# Generated by Django 5.2.7 on 2026-01-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Section')),
                ('link', models.URLField()),
                ('type', models.CharField(choices=[('offer', 'offer'), ('bundle', 'bundle')], default='offer', max_length=10)),
            ],
        ),
    ]
