# Generated by Django 5.2.7 on 2026-01-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_section'),
        ('products', '0006_remove_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['ordering']},
        ),
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
        migrations.RemoveField(
            model_name='section',
            name='link',
        ),
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
        migrations.AddField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('most_sold', 'الاكثر مبيعاً'), ('newest', 'الاحدث'), ('category', 'صنف'), ('selected', 'مختارة')], default='selected', max_length=20),
        ),
    ]
