# Generated by Django 5.2.7 on 2026-03-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_brand_slug_alter_bundle_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_covers', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
