# Generated by Django 5.2.7 on 2026-04-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_brand_cover_image_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='seo_canonical_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_description',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo', verbose_name='SEO Image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='seo_canonical_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='seo_description',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo', verbose_name='SEO Image'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_canonical_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo', verbose_name='SEO Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seo_canonical_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seo_description',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo', verbose_name='SEO Image'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_canonical_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo', verbose_name='SEO Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Title'),
        ),
    ]
